[package]
name = "wrought"
version = "0.1.2"
authors = ["Kyle Brown <kylebrw@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "A Rust implementation of the Wrought compiler"
homepage = "https://github.com/wrought-lang/wrought-rs"
repository = "https://github.com/wrought-lang/wrought-rs"
readme = "README.md"

[dependencies]
clap = { version = "3.0.0-rc.7", features = ["derive"] }
logos = "0.12.0"
miette = { version = "3.3.0", features = ["fancy"] }
thiserror = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.1.0"
